<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'API access token' => '',
  'Email' => '电子邮件',
  'Expire At' => '',
  'Not Active' => '',
  'Password' => '',
  'Roles' => '',
  'Token' => '',
  '"{attribute}" must be a valid JSON' => '"{attribute}" 必须是一个有效的JSON格式',
  'Active' => '活动',
  'Article ID' => '文章ID',
  'Article View' => '文章浏览',
  'Author' => '作者',
  'Base URL' => 'Base URL',
  'Base Url' => 'Base Url',
  'Body' => '正文',
  'Caption' => '标题',
  'Carousel ID' => 'Carousel ID',
  'Category' => '分类',
  'Comment' => '评论',
  'Component' => '组件',
  'Config' => '配置',
  'Created At' => '创建时间',
  'Created at' => '创建时间',
  'Deleted' => '删除',
  'Down to maintenance.' => '维护中',
  'E-mail' => 'E-mail',
  'File Type' => '文件类型',
  'Firstname' => '名字',
  'Gender' => '性别',
  'ID' => 'ID',
  'Image' => '图片',
  'Key' => '键',
  'Last login' => '上次登录',
  'Lastname' => '姓',
  'Locale' => '本地',
  'Middlename' => '中间名',
  'Name' => '名字',
  'Order' => 'Order',
  'Page View' => '页面浏览',
  'Parent Category' => '上级分类',
  'Path' => 'Path',
  'Picture' => '照片',
  'Published' => '发布',
  'Published At' => '发布时间',
  'Size' => 'Size',
  'Slug' => '别名(Slug)',
  'Status' => '状态',
  'Thumbnail' => '缩率图',
  'Title' => '标题',
  'Type' => 'Type',
  'Updated At' => '更新时间',
  'Updated at' => '更新时间',
  'Updater' => '上传者',
  'Upload Ip' => 'Upload Ip',
  'Url' => 'Url',
  'User ID' => '用户 ID',
  'Username' => '用户名',
  'Value' => '值',


  'Attachments' => '附件',
  'View Detail' => '查看详情',

  'a new article ( {model_name} ) was created!' => '新文章 ( {model_name} ) 被创建 !',
  'article ( {model_name} ) was updated!' => '文章 ( {model_name} ) 被更新 !',
  '{created_time} : {created_by} created a new article ( {model_name} )' => '{created_time} : {created_by} 创建了新文章 ( {model_name} )',
  '{created_time} : {created_by} article ( {model_name} ) was updated' => '{created_time} : {created_by} 文章 ( {model_name} ) 被更新',
  'article ( {model_name} ) was deleted!' => '文章 ( {model_name} ) 被删除',
  '{created_time} : article ( {model_name} ) was deleted by user {deleted_by}' => '{created_time} : 文章 ( {model_name} ) 被用户{deleted_by}删除了',

  'Successful Case' => '成功案例',
  'Thumbnail Base Url' => '缩略图基础URL',
  'Thumbnail Path' => '缩略图路径',
  'Create' => '创建',
  'Create {modelClass}' => '创建 {modelClass}',
  'Update' => '更新',
  'Update {modelClass}: ' => '更新 {modelClass}:',
  'Delete' => '删除',

  'Album' => '相册',
  'Album Category' => '相册分类',
  'Category ID' => '分类ID',
  'Parent ID' => '上级ID',
  'Description' => '描述',

  'Draft' => '未激活',
  'Change Password' => '修改密码',

  'Contact Us' => '联系我们',
  'Business Handing' => '业务办理',

  'Customer Name' => '客户姓名',
  'Customer Phone' => '客户联系电话',
  'Progress' => '进度',

  'Progress New' => '新提交',
  'Progress Doing' => '正在处理',
  'Progress Finished' => '处理完成',
  'Progress Exception' => '异常',
  'In Use' => '有效',
  'Not Used' => '无效的',
  'Print' => '打印',
  'captcha' => '验证码',

];
